site_name: PagerDuty plugin for Backstage
theme: 
  name: material
  logo: 'assets/pd-logo.png'
  favicon: 'assets/favicon.png'
  font:
    text: 'Open Sans'

  features:
    - content.action.edit

  palette: 
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle: 
        icon: material/toggle-switch
        name: Swith to dark mode
      primary: custom
      accent: custom
    
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Swith to light mode
      primary: custom
      accent: custom    
  
extra_css:
    - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://backstage.spotify.com/marketplace/pagerduty/plugin/pagerduty
    - icon: fontawesome/brands/discord
      link: https://discord.com/servers/backstage-687207715902193673
    - icon: fontawesome/brands/github
      link: https://github.com/PagerDuty/backstage-plugin-docs